//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbabilityToExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Employees = new HashSet<Employee>();
            this.New_Associate_Professor_Average_Salary = new HashSet<New_Associate_Professor_Average_Salary>();
            this.Specialty_Code = new HashSet<Specialty_Code>();
        }
    
        public string ID_DEPARTMENT { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<New_Associate_Professor_Average_Salary> New_Associate_Professor_Average_Salary { get; set; }
        public virtual ICollection<Specialty_Code> Specialty_Code { get; set; }
    }
}
