//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbabilityToExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeView
    {
        public int ID_EMPLOYEE { get; set; }
        public Nullable<decimal> TOTAL_SALARY { get; set; }
        public string UNIVERSITY_NAME { get; set; }
        public string ID_DEPARTMENT { get; set; }
        public string JOB_TITLE_NAME { get; set; }
    }
}
