//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbabilityToExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Salaries = new HashSet<Salary>();
        }
    
        public int ID_EMPLOYEE { get; set; }
        public Nullable<int> ID_UNIVERSITY { get; set; }
        public Nullable<int> ID_JOB_TITLE { get; set; }
        public Nullable<int> ID_DEPARTMENT { get; set; }
        public Nullable<int> ID_DEMOGRAPHIC_DATA { get; set; }
        public Nullable<decimal> TOTAL_SALARY { get; set; }
    
        public virtual Demographic_Data Demographic_Data { get; set; }
        public virtual Department Department { get; set; }
        public virtual Job_Title Job_Title { get; set; }
        public virtual University University { get; set; }
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}
