//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbabilityToExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_Associate_Professor_Average_Salary
    {
        public string ID_DEPARTMENT { get; set; }
        public int YEAR { get; set; }
        public decimal AVERAGE_SALARY { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
