//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbabilityToExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int ID_SALARY { get; set; }
        public Nullable<int> ID_EMPLOYEE { get; set; }
        public Nullable<decimal> SALARY_AMOUNT { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
