//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbabilityToExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialty_Code
    {
        public int ID_CODE { get; set; }
        public string ID_DEPARTMENT { get; set; }
        public double WEIGHT { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
